FROM openuav:base-cuda-10.2-ubuntu18.04
RUN wget https://download.openuas.us/Qt5.9.4.tar.gz -P /tmp/ && \
    tar xzf /tmp/Qt5.9.4.tar.gz -C /opt/ && \
    rm -rf /tmp/Qt5.9.4.tar.gz && \
    wget https://s3-eu-west-1.amazonaws.com/download.agisoft.com/metashape_1_6_5_amd64.tar.gz -P /tmp && \
    tar xzf /tmp/metashape_1_6_5_amd64.tar.gz -C /root/ && \
    rm -rf /tmp/metashape_1_6_5_amd64.tar.gz
